{'api_version': 'v1',
 'items': [{'action': 'Binding',
            'api_version': None,
            'count': None,
            'event_time': datetime.datetime(2023, 1, 9, 5, 32, 38, 461209, tzinfo=tzutc()),
            'first_timestamp': None,
            'involved_object': {'api_version': 'v1',
                                'field_path': None,
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd',
                                'namespace': 'default',
                                'resource_version': '63321',
                                'uid': '6cec826f-e9cc-4e5c-8054-8a2daf84c516'},
            'kind': None,
            'last_timestamp': None,
            'message': 'Successfully assigned '
                       'default/source-streaming-deployment-7c57ffbd6b-n9wgd '
                       'to minikube',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'events.k8s.io/v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:action': {},
                                                           'f:eventTime': {},
                                                           'f:note': {},
                                                           'f:reason': {},
                                                           'f:regarding': {},
                                                           'f:reportingController': {},
                                                           'f:reportingInstance': {},
                                                           'f:type': {}},
                                             'manager': 'kube-scheduler',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd.17388d0f4f37b8ee',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63330',
                         'self_link': None,
                         'uid': '15448208-6175-428a-b5ff-8425e9796ffc'},
            'reason': 'Scheduled',
            'related': None,
            'reporting_component': 'default-scheduler',
            'reporting_instance': 'default-scheduler-minikube',
            'series': None,
            'source': {'component': None, 'host': None},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 39, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd',
                                'namespace': 'default',
                                'resource_version': '63324',
                                'uid': '6cec826f-e9cc-4e5c-8054-8a2daf84c516'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 39, tzinfo=tzutc()),
            'message': 'Pulling image "hctung57/source-streaming-ffmpeg:1.0"',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 39, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 32, 39, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd.17388d0f73e82233',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63333',
                         'self_link': None,
                         'uid': 'ee435970-4df8-4659-8f23-6e4da740b359'},
            'reason': 'Pulling',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd',
                                'namespace': 'default',
                                'resource_version': '63324',
                                'uid': '6cec826f-e9cc-4e5c-8054-8a2daf84c516'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
            'message': 'Successfully pulled image '
                       '"hctung57/source-streaming-ffmpeg:1.0" in '
                       '1m3.31832949s',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd.17388d1e31f95eba',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63379',
                         'self_link': None,
                         'uid': '0b38aa39-cabe-45bf-85cc-e5497de40706'},
            'reason': 'Pulled',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd',
                                'namespace': 'default',
                                'resource_version': '63324',
                                'uid': '6cec826f-e9cc-4e5c-8054-8a2daf84c516'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
            'message': 'Created container source-streaming',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd.17388d1e344b9569',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63380',
                         'self_link': None,
                         'uid': 'f0cdd1e8-6aff-4515-87c5-b423f82571ff'},
            'reason': 'Created',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd',
                                'namespace': 'default',
                                'resource_version': '63324',
                                'uid': '6cec826f-e9cc-4e5c-8054-8a2daf84c516'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
            'message': 'Started container source-streaming',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 33, 42, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-n9wgd.17388d1e3cc68644',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63381',
                         'self_link': None,
                         'uid': '16b63bff-87c7-406c-9308-45ff9efe023d'},
            'reason': 'Started',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 8, 15, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-ncnj9',
                                'namespace': 'default',
                                'resource_version': '61756',
                                'uid': '0d92f987-0111-41be-9271-9f316f5bd098'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 8, 15, tzinfo=tzutc()),
            'message': 'Stopping container source-streaming',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 8, 15, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 8, 15, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-ncnj9.17388bba93020067',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62208',
                         'self_link': None,
                         'uid': 'e509c978-5c92-4316-ab6e-54f0b4713563'},
            'reason': 'Killing',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': 'Binding',
            'api_version': None,
            'count': None,
            'event_time': datetime.datetime(2023, 1, 9, 5, 9, 23, 137454, tzinfo=tzutc()),
            'first_timestamp': None,
            'involved_object': {'api_version': 'v1',
                                'field_path': None,
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg',
                                'namespace': 'default',
                                'resource_version': '62266',
                                'uid': '3fa8d9fc-9d01-49d3-a233-0a8698d4efcb'},
            'kind': None,
            'last_timestamp': None,
            'message': 'Successfully assigned '
                       'default/source-streaming-deployment-7c57ffbd6b-pzxcg '
                       'to minikube',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'events.k8s.io/v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:action': {},
                                                           'f:eventTime': {},
                                                           'f:note': {},
                                                           'f:reason': {},
                                                           'f:regarding': {},
                                                           'f:reportingController': {},
                                                           'f:reportingInstance': {},
                                                           'f:type': {}},
                                             'manager': 'kube-scheduler',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg.17388bca6f70f38c',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62274',
                         'self_link': None,
                         'uid': '7f972039-e791-4435-b1df-8f8b4a16be82'},
            'reason': 'Scheduled',
            'related': None,
            'reporting_component': 'default-scheduler',
            'reporting_instance': 'default-scheduler-minikube',
            'series': None,
            'source': {'component': None, 'host': None},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg',
                                'namespace': 'default',
                                'resource_version': '62268',
                                'uid': '3fa8d9fc-9d01-49d3-a233-0a8698d4efcb'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
            'message': 'Pulling image "hctung57/source-streaming-ffmpeg:1.0"',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg.17388bca9537d4b4',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62279',
                         'self_link': None,
                         'uid': '220404be-c75d-465c-8de5-a52200e0ea34'},
            'reason': 'Pulling',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg',
                                'namespace': 'default',
                                'resource_version': '62268',
                                'uid': '3fa8d9fc-9d01-49d3-a233-0a8698d4efcb'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc()),
            'message': 'Successfully pulled image '
                       '"hctung57/source-streaming-ffmpeg:1.0" in '
                       '1m3.096772803s',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg.17388bd94614618a',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62354',
                         'self_link': None,
                         'uid': '21abd34d-8329-4189-82bb-912772f71774'},
            'reason': 'Pulled',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg',
                                'namespace': 'default',
                                'resource_version': '62268',
                                'uid': '3fa8d9fc-9d01-49d3-a233-0a8698d4efcb'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc()),
            'message': 'Created container source-streaming',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 10, 26, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg.17388bd948846223',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62355',
                         'self_link': None,
                         'uid': '10f5e273-7e2f-4554-b5eb-17f8c823098c'},
            'reason': 'Created',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 27, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg',
                                'namespace': 'default',
                                'resource_version': '62268',
                                'uid': '3fa8d9fc-9d01-49d3-a233-0a8698d4efcb'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 27, tzinfo=tzutc()),
            'message': 'Started container source-streaming',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 10, 27, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 10, 27, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg.17388bd94e76b33a',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62356',
                         'self_link': None,
                         'uid': '3648cd6d-2295-45a8-90cb-3ccea5ede11e'},
            'reason': 'Started',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 31, 4, tzinfo=tzutc()),
            'involved_object': {'api_version': 'v1',
                                'field_path': 'spec.containers{source-streaming}',
                                'kind': 'Pod',
                                'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg',
                                'namespace': 'default',
                                'resource_version': '62268',
                                'uid': '3fa8d9fc-9d01-49d3-a233-0a8698d4efcb'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 31, 4, tzinfo=tzutc()),
            'message': 'Stopping container source-streaming',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 31, 4, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {},
                                                                        'f:host': {}},
                                                           'f:type': {}},
                                             'manager': 'kubelet',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 31, 4, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b-pzxcg.17388cf966e40e32',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63241',
                         'self_link': None,
                         'uid': '4e91b48f-03b5-416e-b98d-00f9369333c1'},
            'reason': 'Killing',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'kubelet', 'host': 'minikube'},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
            'involved_object': {'api_version': 'apps/v1',
                                'field_path': None,
                                'kind': 'ReplicaSet',
                                'name': 'source-streaming-deployment-7c57ffbd6b',
                                'namespace': 'default',
                                'resource_version': '62262',
                                'uid': 'a38cf521-a98f-45e7-a552-deb7d17a402e'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
            'message': 'Created pod: '
                       'source-streaming-deployment-7c57ffbd6b-pzxcg',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {}},
                                                           'f:type': {}},
                                             'manager': 'kube-controller-manager',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b.17388bca6efab4a0',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62269',
                         'self_link': None,
                         'uid': 'f79b5e63-db0a-497c-b557-6b340f571932'},
            'reason': 'SuccessfulCreate',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'replicaset-controller', 'host': None},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
            'involved_object': {'api_version': 'apps/v1',
                                'field_path': None,
                                'kind': 'ReplicaSet',
                                'name': 'source-streaming-deployment-7c57ffbd6b',
                                'namespace': 'default',
                                'resource_version': '63317',
                                'uid': '6c1cccef-35f3-47bf-8035-62e80bfe1f98'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
            'message': 'Created pod: '
                       'source-streaming-deployment-7c57ffbd6b-n9wgd',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {}},
                                                           'f:type': {}},
                                             'manager': 'kube-controller-manager',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment-7c57ffbd6b.17388d0f4f010b0a',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63323',
                         'self_link': None,
                         'uid': 'a602be4a-5c21-44da-abc8-d6812655e818'},
            'reason': 'SuccessfulCreate',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'replicaset-controller', 'host': None},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
            'involved_object': {'api_version': 'apps/v1',
                                'field_path': None,
                                'kind': 'Deployment',
                                'name': 'source-streaming-deployment',
                                'namespace': 'default',
                                'resource_version': '62261',
                                'uid': 'fa11e6f6-e48e-4743-8cb6-92d926eb86d3'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
            'message': 'Scaled up replica set '
                       'source-streaming-deployment-7c57ffbd6b to 1',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {}},
                                                           'f:type': {}},
                                             'manager': 'kube-controller-manager',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 9, 23, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment.17388bca6ea49a77',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '62263',
                         'self_link': None,
                         'uid': '0ae64a0a-df86-4f6e-b477-17848aab57a0'},
            'reason': 'ScalingReplicaSet',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'deployment-controller', 'host': None},
            'type': 'Normal'},
           {'action': None,
            'api_version': None,
            'count': 1,
            'event_time': None,
            'first_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
            'involved_object': {'api_version': 'apps/v1',
                                'field_path': None,
                                'kind': 'Deployment',
                                'name': 'source-streaming-deployment',
                                'namespace': 'default',
                                'resource_version': '63316',
                                'uid': '23cbbd08-8d7b-4f15-a18e-4d2163e4c1eb'},
            'kind': None,
            'last_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
            'message': 'Scaled up replica set '
                       'source-streaming-deployment-7c57ffbd6b to 1',
            'metadata': {'annotations': None,
                         'creation_timestamp': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc()),
                         'deletion_grace_period_seconds': None,
                         'deletion_timestamp': None,
                         'finalizers': None,
                         'generate_name': None,
                         'generation': None,
                         'labels': None,
                         'managed_fields': [{'api_version': 'v1',
                                             'fields_type': 'FieldsV1',
                                             'fields_v1': {'f:count': {},
                                                           'f:firstTimestamp': {},
                                                           'f:involvedObject': {},
                                                           'f:lastTimestamp': {},
                                                           'f:message': {},
                                                           'f:reason': {},
                                                           'f:source': {'f:component': {}},
                                                           'f:type': {}},
                                             'manager': 'kube-controller-manager',
                                             'operation': 'Update',
                                             'subresource': None,
                                             'time': datetime.datetime(2023, 1, 9, 5, 32, 38, tzinfo=tzutc())}],
                         'name': 'source-streaming-deployment.17388d0f4ea7848b',
                         'namespace': 'default',
                         'owner_references': None,
                         'resource_version': '63319',
                         'self_link': None,
                         'uid': '8eb8cf43-dbc4-4899-8cfa-ff5890b050f9'},
            'reason': 'ScalingReplicaSet',
            'related': None,
            'reporting_component': '',
            'reporting_instance': '',
            'series': None,
            'source': {'component': 'deployment-controller', 'host': None},
            'type': 'Normal'}],
 'kind': 'EventList',
 'metadata': {'_continue': None,
              'remaining_item_count': None,
              'resource_version': '64535',
              'self_link': None}}